name: Integration Tests
on: push
jobs:
  go-tests:
    name: Run Go Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'
      - uses: autero1/action-terraform@v1.1.0
        with:
          terraform_version: 1.2.8
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: go test -v -timeout 30m